# تنظیم برای victim.lab
<VirtualHost *:80>
    ServerName victim.lab
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>

# تنظیم برای attacker.lab
<VirtualHost *:80>
    ServerName attacker.lab
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8002/
    ProxyPassReverse / http://127.0.0.1:8002/
</VirtualHost>