server {
    listen 80;
    server_name hackerapp.eitebar.ir;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hackerapp.eitebar.ir;

    ssl_certificate     /etc/nginx/certs/kr-rezvan.ir.pem;
    ssl_certificate_key /etc/nginx/certs/kr-rezvan.ir-key.pem;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}